//-------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by EntitiesToDTOs.v3.3.0.0 (entitiestodtos.codeplex.com).
//     Timestamp: 2016/07/25 - 09:20:15
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//-------------------------------------------------------------------------------------------------------
using System.Text;
using System.Runtime.Serialization;
using System.Collections.Generic;
using System;

namespace WebDataModel.Entities
{
    public partial class clienteDto
    {
        public string v_IdCliente { get; set; }

        public string v_IdVendedor { get; set; }

        public string v_CodCliente { get; set; }

        public string v_FlagPantalla { get; set; }

        public int? i_IdTipoIdentificacion { get; set; }

        public string v_NroDocIdentificacion { get; set; }

        public int? i_IdTipoPersona { get; set; }

        public string v_PrimerNombre { get; set; }

        public string v_SegundoNombre { get; set; }

        public string v_ApePaterno { get; set; }
        
        public string v_ApeMaterno { get; set; }
        
        public string v_RazonSocial { get; set; }
        
        public int? i_IdSexo { get; set; }
        
        public string v_DirecPrincipal { get; set; }
        
        public int? i_IdPais { get; set; }
        
        public int? i_IdDepartamento { get; set; }
        
        public int? i_IdProvincia { get; set; }
        
        public int? i_IdDistrito { get; set; }
        
        public string v_DirecSecundaria { get; set; }
        
        public string v_TelefonoFijo { get; set; }
       
        public string v_TelefonoFax { get; set; }
   
        public string v_TelefonoMovil { get; set; }
        
        public string v_Correo { get; set; }
        
        public string v_PaginaWeb { get; set; }

        public int? i_Activo { get; set; }
       
        public DateTime? t_FechaNacimiento { get; set; }

        public int? i_Nacionalidad { get; set; }
        
        public string v_NombreContacto { get; set; }
        
        public int? i_IdGrupoCliente { get; set; }
        
        public int? i_IdListaPrecios { get; set; }
        
        public int? i_IdZona { get; set; }
        
        public int? i_EsPrestadorServicios { get; set; }
        
        public string v_Servicio { get; set; }
        
        public int? i_IdConvenioDobleTributacion { get; set; }
        
        public int? i_AfectoDetraccion { get; set; }
      
        public int? i_UsaLineaCredito { get; set; }
     
        public int? i_Eliminado { get; set; }

        public string v_NroCuentaDetraccion { get; set; }
        
        public DateTime? t_InsertaFecha { get; set; }

        public clienteDto()
        {
        }
    }
}