//-------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by EntitiesToDTOs.v3.2 (entitiestodtos.codeplex.com).
//     Timestamp: 2016/07/22 - 16:46:22
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//-------------------------------------------------------------------------------------------------------
using System;

namespace WebDataModel.Entities
{
    public partial class configuracionfacturacionDto
    {
        
        public Int32 i_Idconfiguracionfacturacion { get; set; }

        
        public String v_Ruc { get; set; }

        
        public String v_Usuario { get; set; }

        
        public String v_Clave { get; set; }

        
        public String v_RazonSocial { get; set; }

        
        public String v_NombreComercial { get; set; }

        
        public String v_Domicilio { get; set; }

        
        public String v_Urbanizacion { get; set; }

        
        public String v_Ubigueo { get; set; }

        
        public String v_Departamento { get; set; }

        
        public String v_Provincia { get; set; }

        
        public String v_Distrito { get; set; }

        
        public String v_ClaveCertificado { get; set; }

        
        public Byte[] b_FileCertificado { get; set; }

        
        public Nullable<Int16> i_EsEmisor { get; set; }

        
        public Nullable<Int32> i_GroupUndInter { get; set; }

        
        public Nullable<Int32> i_GroupNCR { get; set; }

        
        public Nullable<Int32> i_GroupNDB { get; set; }

        
        public Nullable<Int16> i_TipoServicio { get; set; }

        
        public Byte[] b_Logo { get; set; }

        
        public String v_Web { get; set; }

        
        public String v_Resolucion { get; set; }

        public configuracionfacturacionDto()
        {
        }
    }
}
