//-------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by EntitiesToDTOs.v3.2 (entitiestodtos.codeplex.com).
//     Timestamp: 2016/07/22 - 16:46:25
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//-------------------------------------------------------------------------------------------------------
using System;

namespace WebDataModel.Entities
{
    public partial class ventadetalleDto
    {        
        public String v_IdVentaDetalle { get; set; }
       
        public String v_IdVenta { get; set; }
       
        public String v_IdMovimientoDetalle { get; set; }
        
        public String v_IdDiarioDetalle { get; set; }
        
        public Nullable<Int32> i_IdAlmacen { get; set; }
        
        public String v_NroCuenta { get; set; }
        
        public Nullable<Int32> i_Anticipio { get; set; }
        
        public String v_IdProductoDetalle { get; set; }
        
        public String v_DescripcionProducto { get; set; }
        
        public Nullable<Decimal> d_Cantidad { get; set; }
      
        public Nullable<Decimal> d_CantidadEmpaque { get; set; }
        
        public Nullable<Int32> i_IdUnidadMedida { get; set; }
        
        public Nullable<Decimal> d_Precio { get; set; }
       
        public Nullable<Decimal> d_Valor { get; set; }
        
        public Nullable<Decimal> d_ValorVenta { get; set; }
        
        public Nullable<Decimal> d_Descuento { get; set; }
        
        public Nullable<Decimal> d_Igv { get; set; }
       
        public Nullable<Decimal> d_PrecioVenta { get; set; }
        
        public Nullable<Decimal> d_PrecioImpresion { get; set; }
        
        public Nullable<Decimal> d_Percepcion { get; set; }
        
        public Nullable<Decimal> d_isc { get; set; }
        
        public Nullable<Decimal> d_otrostributos { get; set; }
       
        public Nullable<Int32> i_IdMonedaLP { get; set; }
        
        public Nullable<Int32> i_IdTipoOperacion { get; set; }
       
        public Nullable<Int32> i_IdTipoOperacionAnexo { get; set; }
        
        public Nullable<Int32> i_NroUnidades { get; set; }
        
        public Nullable<Decimal> d_PorcentajeComision { get; set; }
        
        public String v_Observaciones { get; set; }
        
        public String v_PedidoExportacion { get; set; }
       
        public String v_FacturaRef { get; set; }
       
        public String i_IdCentroCosto { get; set; }
        
        public Nullable<Int32> i_Eliminado { get; set; }
        
        public Nullable<Int32> i_InsertaIdUsuario { get; set; }
        
        public Nullable<DateTime> t_InsertaFecha { get; set; }
       
        public Nullable<Int32> i_ActualizaIdUsuario { get; set; }
       
        public Nullable<DateTime> t_ActualizaFecha { get; set; }
        
        public String venta_v_IdVenta { get; set; }

        public ventadetalleDto()
        {
        }

        public ventadetalleDto(String v_IdVentaDetalle, String v_IdVenta, String v_IdMovimientoDetalle, String v_IdDiarioDetalle, Nullable<Int32> i_IdAlmacen, String v_NroCuenta, Nullable<Int32> i_Anticipio, String v_IdProductoDetalle, String v_DescripcionProducto, Nullable<Decimal> d_Cantidad, Nullable<Decimal> d_CantidadEmpaque, Nullable<Int32> i_IdUnidadMedida, Nullable<Decimal> d_Precio, Nullable<Decimal> d_Valor, Nullable<Decimal> d_ValorVenta, Nullable<Decimal> d_Descuento, Nullable<Decimal> d_Igv, Nullable<Decimal> d_PrecioVenta, Nullable<Decimal> d_PrecioImpresion, Nullable<Decimal> d_Percepcion, Nullable<Decimal> d_isc, Nullable<Decimal> d_otrostributos, Nullable<Int32> i_IdMonedaLP, Nullable<Int32> i_IdTipoOperacion, Nullable<Int32> i_IdTipoOperacionAnexo, Nullable<Int32> i_NroUnidades, Nullable<Decimal> d_PorcentajeComision, String v_Observaciones, String v_PedidoExportacion, String v_FacturaRef, String i_IdCentroCosto, Nullable<Int32> i_Eliminado, Nullable<Int32> i_InsertaIdUsuario, Nullable<DateTime> t_InsertaFecha, Nullable<Int32> i_ActualizaIdUsuario, Nullable<DateTime> t_ActualizaFecha, String venta_v_IdVenta)
        {
			this.v_IdVentaDetalle = v_IdVentaDetalle;
			this.v_IdVenta = v_IdVenta;
			this.v_IdMovimientoDetalle = v_IdMovimientoDetalle;
			this.v_IdDiarioDetalle = v_IdDiarioDetalle;
			this.i_IdAlmacen = i_IdAlmacen;
			this.v_NroCuenta = v_NroCuenta;
			this.i_Anticipio = i_Anticipio;
			this.v_IdProductoDetalle = v_IdProductoDetalle;
			this.v_DescripcionProducto = v_DescripcionProducto;
			this.d_Cantidad = d_Cantidad;
			this.d_CantidadEmpaque = d_CantidadEmpaque;
			this.i_IdUnidadMedida = i_IdUnidadMedida;
			this.d_Precio = d_Precio;
			this.d_Valor = d_Valor;
			this.d_ValorVenta = d_ValorVenta;
			this.d_Descuento = d_Descuento;
			this.d_Igv = d_Igv;
			this.d_PrecioVenta = d_PrecioVenta;
			this.d_PrecioImpresion = d_PrecioImpresion;
			this.d_Percepcion = d_Percepcion;
			this.d_isc = d_isc;
			this.d_otrostributos = d_otrostributos;
			this.i_IdMonedaLP = i_IdMonedaLP;
			this.i_IdTipoOperacion = i_IdTipoOperacion;
			this.i_IdTipoOperacionAnexo = i_IdTipoOperacionAnexo;
			this.i_NroUnidades = i_NroUnidades;
			this.d_PorcentajeComision = d_PorcentajeComision;
			this.v_Observaciones = v_Observaciones;
			this.v_PedidoExportacion = v_PedidoExportacion;
			this.v_FacturaRef = v_FacturaRef;
			this.i_IdCentroCosto = i_IdCentroCosto;
			this.i_Eliminado = i_Eliminado;
			this.i_InsertaIdUsuario = i_InsertaIdUsuario;
			this.t_InsertaFecha = t_InsertaFecha;
			this.i_ActualizaIdUsuario = i_ActualizaIdUsuario;
			this.t_ActualizaFecha = t_ActualizaFecha;
			this.venta_v_IdVenta = venta_v_IdVenta;
        }
    }
}
