//-------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by EntitiesToDTOs.v3.2 (entitiestodtos.codeplex.com).
//     Timestamp: 2016/07/22 - 16:46:25
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//-------------------------------------------------------------------------------------------------------
using System;

namespace WebDataModel.Entities
{
    public partial class ventadetalleDto
    {        
        public String v_IdVentaDetalle { get; set; }
       
        public String v_IdVenta { get; set; }
       
        public String v_IdMovimientoDetalle { get; set; }
        
        public String v_IdDiarioDetalle { get; set; }
        
        public Nullable<Int32> i_IdAlmacen { get; set; }
        
        public String v_NroCuenta { get; set; }
        
        public Nullable<Int32> i_Anticipio { get; set; }
        
        public String v_IdProductoDetalle { get; set; }
        
        public String v_DescripcionProducto { get; set; }
        
        public Nullable<Decimal> d_Cantidad { get; set; }
      
        public Nullable<Decimal> d_CantidadEmpaque { get; set; }
        
        public Nullable<Int32> i_IdUnidadMedida { get; set; }
        
        public Nullable<Decimal> d_Precio { get; set; }
       
        public Nullable<Decimal> d_Valor { get; set; }
        
        public Nullable<Decimal> d_ValorVenta { get; set; }
        
        public Nullable<Decimal> d_Descuento { get; set; }
        
        public Nullable<Decimal> d_Igv { get; set; }
       
        public Nullable<Decimal> d_PrecioVenta { get; set; }
        
        public Nullable<Decimal> d_PrecioImpresion { get; set; }
        
        public Nullable<Decimal> d_Percepcion { get; set; }
        
        public Nullable<Decimal> d_isc { get; set; }
        
        public Nullable<Decimal> d_otrostributos { get; set; }
       
        public Nullable<Int32> i_IdMonedaLP { get; set; }
        
        public Nullable<Int32> i_IdTipoOperacion { get; set; }
       
        public Nullable<Int32> i_IdTipoOperacionAnexo { get; set; }
        
        public Nullable<Int32> i_NroUnidades { get; set; }
        
        public Nullable<Decimal> d_PorcentajeComision { get; set; }
        
        public String v_Observaciones { get; set; }
        
        public String v_PedidoExportacion { get; set; }
       
        public String v_FacturaRef { get; set; }
       
        public String i_IdCentroCosto { get; set; }
        
        public Nullable<Int32> i_Eliminado { get; set; }
        
        public Nullable<Int32> i_InsertaIdUsuario { get; set; }
        
        public Nullable<DateTime> t_InsertaFecha { get; set; }
       
        public Nullable<Int32> i_ActualizaIdUsuario { get; set; }
       
        public Nullable<DateTime> t_ActualizaFecha { get; set; }
        
        public String venta_v_IdVenta { get; set; }

        public ventadetalleDto()
        {
        }
    }
}
