//-------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by EntitiesToDTOs.v3.2 (entitiestodtos.codeplex.com).
//     Timestamp: 2016/07/22 - 16:46:26
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//-------------------------------------------------------------------------------------------------------
using System;

namespace WebDataModel.Entities
{
    public partial class ventahomolagacionDto
    {
        
        public Int32 i_IdVentaHomologacion { get; set; }

        
        public Byte[] b_FileXml { get; set; }

        
        public String v_IdVenta { get; set; }

        
        public String v_Ticket { get; set; }

        
        public Byte[] b_ResponseTicket { get; set; }

        
        public String venta_v_IdVenta { get; set; }

        public ventahomolagacionDto()
        {
        }

        public ventahomolagacionDto(Int32 i_IdVentaHomologacion, Byte[] b_FileXml, String v_IdVenta, String v_Ticket, Byte[] b_ResponseTicket, String venta_v_IdVenta)
        {
			this.i_IdVentaHomologacion = i_IdVentaHomologacion;
			this.b_FileXml = b_FileXml;
			this.v_IdVenta = v_IdVenta;
			this.v_Ticket = v_Ticket;
			this.b_ResponseTicket = b_ResponseTicket;
			this.venta_v_IdVenta = venta_v_IdVenta;
        }
    }
}
