//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebBusinessLayer.Querys {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Query_SqlServer {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Query_SqlServer() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WebBusinessLayer.Querys.Query.SqlServer", typeof(Query_SqlServer).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a SELECT * FROM cliente WHERE v_IdCliente = @id.
        /// </summary>
        internal static string GetClient {
            get {
                return ResourceManager.GetString("GetClient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a SELECT v_IdCliente FROM cliente WHERE v_NroDocIdentificacion = @id AND v_Password=@pass.
        /// </summary>
        internal static string GetIdClient {
            get {
                return ResourceManager.GetString("GetIdClient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a SELECT v_IdVenta FROM venta WHERE i_IdTipoDocumento=@tipoDoc AND  v_SerieDocumento=@serie AND v_CorrelativoDocumento=@correlativo AND t_FechaRegistro=@fecha AND d_Total=@total.
        /// </summary>
        internal static string GetIdVenta {
            get {
                return ResourceManager.GetString("GetIdVenta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a SELECT i.d_Monto, i.d_Porcentaje, i.i_IdSistemaIsc FROM productodetalle p
        ///                            LEFT OUTER JOIN productoisc i ON p.v_IdProducto = i.v_IdProducto
        ///                            WHERE p.v_IdProductoDetalle = @id  AND  i.v_Periodo = @periodo;.
        /// </summary>
        internal static string GetIscFromDetail {
            get {
                return ResourceManager.GetString("GetIscFromDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a SELECT * FROM venta WHERE v_SerieDocumento LIKE &apos;[FB]%&apos; AND v_IdCliente=@id.
        /// </summary>
        internal static string GetListFromClient {
            get {
                return ResourceManager.GetString("GetListFromClient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a SELECT v_Ruc, v_RazonSocial, v_NombreComercial, v_Domicilio, v_Resolucion FROM configuracionfacturacion.
        /// </summary>
        internal static string GetLite {
            get {
                return ResourceManager.GetString("GetLite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a SELECT v.*, vd.*, 
        ///                                c.v_IdCliente, c.i_IdTipoIdentificacion, c.v_NroDocIdentificacion, c.v_PrimerNombre, c.v_SegundoNombre, c.v_ApePaterno, c.v_ApeMaterno, c.v_RazonSocial, c.v_DirecPrincipal,
        ///                                d1.v_Value1, d2.v_Value1 FROM venta v
        ///                                LEFT OUTER JOIN cliente c ON v.v_IdCliente = c.v_IdCliente
        ///                                LEFT OUTER JOIN ventadetalle vd ON v.v_IdVenta = vd.v_IdVenta
        ///                             [resto de la cadena truncado]&quot;;.
        /// </summary>
        internal static string GetReporteInvoice {
            get {
                return ResourceManager.GetString("GetReporteInvoice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a SELECT * FROM venta WHERE v_IdVenta=@idVenta.
        /// </summary>
        internal static string GetVenta {
            get {
                return ResourceManager.GetString("GetVenta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a SELECT v.*, c.i_IdTipoIdentificacion,c.v_NroDocIdentificacion,c.v_ApePaterno,
        ///                        c.v_ApeMaterno,c.v_PrimerNombre,c.v_SegundoNombre, c.v_RazonSocial, d.v_Value1 FROM venta v 
        ///                        LEFT OUTER JOIN cliente c ON v.v_IdCliente = c.v_IdCliente
        ///                        LEFT OUTER JOIN datahierarchy d ON v.i_IdIgv = d.i_ItemId AND d.i_GroupId = 27
        ///                        WHERE v.v_IdVenta = @idVenta.
        /// </summary>
        internal static string GetVentaCliente {
            get {
                return ResourceManager.GetString("GetVentaCliente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a SELECT v.*, d2.v_Value2, d3.v_Value2 FROM ventadetalle v
        ///                        LEFT OUTER JOIN datahierarchy d on v.i_IdUnidadMedida = d.i_ItemId AND d.i_GroupId = 17
        ///                        LEFT OUTER JOIN datahierarchy d2 on d.i_ParentItemId = d2.i_ItemId AND d2.i_GroupId = @idg
        ///                        LEFT OUTER JOIN datahierarchy d3 ON v.i_IdTipoOperacion = d3.i_ItemId AND d3.i_GroupId = 35
        ///                        WHERE v.v_IdVenta = @id.
        /// </summary>
        internal static string GetVentaDetalles {
            get {
                return ResourceManager.GetString("GetVentaDetalles", resourceCulture);
            }
        }
    }
}
