//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebBusinessLayer.Querys {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Query_Postgres {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Query_Postgres() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WebBusinessLayer.Querys.Query.Postgres", typeof(Query_Postgres).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a SELECT * FROM cliente WHERE &quot;v_IdCliente&quot; = @id.
        /// </summary>
        internal static string GetClient {
            get {
                return ResourceManager.GetString("GetClient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a SELECT &quot;v_IdCliente&quot; FROM cliente WHERE &quot;v_NroDocIdentificacion&quot; = @id.
        /// </summary>
        internal static string GetIdClient {
            get {
                return ResourceManager.GetString("GetIdClient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a SELECT &quot;v_IdVenta&quot; FROM venta WHERE &quot;i_IdTipoDocumento&quot;=@tipoDoc AND &quot;v_SerieDocumento&quot;=@serie AND &quot;v_CorrelativoDocumento&quot;=@correlativo AND &quot;t_FechaRegistro&quot;=@fecha AND &quot;d_Total&quot;=@total.
        /// </summary>
        internal static string GetIdVenta {
            get {
                return ResourceManager.GetString("GetIdVenta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a SELECT i.&quot;d_Monto&quot;, i.&quot;d_Porcentaje&quot;, i.&quot;i_IdSistemaIsc&quot; FROM productodetalle p
        ///LEFT OUTER JOIN productoisc i ON p.&quot;v_IdProducto&quot; = i.&quot;v_IdProducto&quot;
        ///WHERE p.&quot;v_IdProductoDetalle&quot; = @id  AND  i.&quot;v_Periodo&quot; = @periodo.
        /// </summary>
        internal static string GetIscFromDetail {
            get {
                return ResourceManager.GetString("GetIscFromDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a SELECT * FROM venta WHERE &quot;v_IdCliente&quot;=@id AND (&quot;v_SerieDocumento&quot; LIKE &apos;F%&apos; OR &quot;v_SerieDocumento&quot; LIKE &apos;B%&apos;).
        /// </summary>
        internal static string GetListFromClient {
            get {
                return ResourceManager.GetString("GetListFromClient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a SELECT &quot;v_Ruc&quot;,&quot;v_RazonSocial&quot;,&quot;v_NombreComercial&quot;,&quot;v_Domicilio&quot;,&quot;v_Resolucion&quot; FROM configuracionfacturacion.
        /// </summary>
        internal static string GetLite {
            get {
                return ResourceManager.GetString("GetLite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a SELECT v.*, vd.*,
        ///c.&quot;v_IdCliente&quot;, c.&quot;i_IdTipoIdentificacion&quot;, c.&quot;v_NroDocIdentificacion&quot;, c.&quot;v_PrimerNombre&quot;, c.&quot;v_SegundoNombre&quot;, c.&quot;v_ApePaterno&quot;, c.&quot;v_ApeMaterno&quot;, c.&quot;v_RazonSocial&quot;, c.&quot;v_DirecPrincipal&quot;,
        ///d1.&quot;v_Value1&quot;, d2.&quot;v_Value1&quot; FROM venta v
        ///LEFT OUTER JOIN cliente c ON v.&quot;v_IdCliente&quot;= c.&quot;v_IdCliente&quot;
        ///LEFT OUTER JOIN ventadetalle vd ON v.&quot;v_IdVenta&quot; = vd.&quot;v_IdVenta&quot;
        ///LEFT OUTER JOIN datahierarchy d1 ON  vd.&quot;i_IdUnidadMedida&quot;= d1.&quot;i_ItemId&quot; AND d1.&quot;i_GroupId&quot; = 17
        ///LEFT OUTER JOIN datahierarchy [resto de la cadena truncado]&quot;;.
        /// </summary>
        internal static string GetReporteInvoice {
            get {
                return ResourceManager.GetString("GetReporteInvoice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a SELECT * FROM venta WHERE &quot;v_IdVenta&quot;=@idVenta.
        /// </summary>
        internal static string GetVenta {
            get {
                return ResourceManager.GetString("GetVenta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a SELECT v.*, c.&quot;i_IdTipoIdentificacion&quot;,c.&quot;v_NroDocIdentificacion&quot;,c.&quot;v_ApePaterno&quot;,
        ///c.&quot;v_ApeMaterno&quot;,c.&quot;v_PrimerNombre&quot;,c.&quot;v_SegundoNombre&quot;, c.&quot;v_RazonSocial&quot;, d.&quot;v_Value1&quot; FROM venta v
        ///LEFT OUTER JOIN cliente c ON v.&quot;v_IdCliente&quot; = c.&quot;v_IdCliente&quot;
        ///LEFT OUTER JOIN datahierarchy d ON v.&quot;i_IdIgv&quot; = d.&quot;i_ItemId&quot; AND d.&quot;i_GroupId&quot; = 27
        /// WHERE v.&quot;v_IdVenta&quot; = @idVenta.
        /// </summary>
        internal static string GetVentaCliente {
            get {
                return ResourceManager.GetString("GetVentaCliente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a SELECT v.*, d2.&quot;v_Value2&quot;, d3.&quot;v_Value2&quot; FROM ventadetalle v
        ///LEFT OUTER JOIN datahierarchy d on v.&quot;i_IdUnidadMedida&quot;= d.&quot;i_ItemId&quot; AND d.&quot;i_GroupId&quot;= 17
        ///LEFT OUTER JOIN datahierarchy d2 on d.&quot;i_ParentItemId&quot; = d2.&quot;i_ItemId&quot; AND d2.&quot;i_GroupId&quot; = @idg
        ///LEFT OUTER JOIN datahierarchy d3 ON v.&quot;i_IdTipoOperacion&quot; = d3.&quot;i_ItemId&quot; AND d3.&quot;i_GroupId&quot; = 35
        ///WHERE v.&quot;v_IdVenta&quot; = @id.
        /// </summary>
        internal static string GetVentaDetalles {
            get {
                return ResourceManager.GetString("GetVentaDetalles", resourceCulture);
            }
        }
    }
}
